Traceback (most recent call last):
  File "/home/pi/Desktop/RescueLineMondialiiV3/rescueLine8.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
